/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_974D6591__
#define __PLUGINEDITOR_H_974D6591__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class HiLoFilterAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    HiLoFilterAudioProcessorEditor (HiLoFilterAudioProcessor* ownerFilter);
    ~HiLoFilterAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_974D6591__
